<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Working with PSM data • PSM</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Working with PSM data">
<meta property="og:description" content="PSM">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">PSM</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/psm.html">Working with PSM data</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/RforMassSpectrometry/PSM/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="psm_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Working with PSM data</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/RforMassSpectrometry/PSM/blob/master/vignettes/psm.Rmd"><code>vignettes/psm.Rmd</code></a></small>
      <div class="hidden name"><code>psm.Rmd</code></div>

    </div>

    
    
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  document.querySelector("h1").className = "title";
});
</script><script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  var links = document.links;  
  for (var i = 0, linksLength = links.length; i < linksLength; i++)
    if (links[i].hostname != window.location.hostname)
      links[i].target = '_blank';
});
</script><p><strong>Package</strong>: <em><a href="https://bioconductor.org/packages/3.12/PSM">PSM</a></em><br><strong>Authors</strong>: Laurent Gatto [aut, cre] (<a href="https://orcid.org/0000-0002-1520-2268" class="uri">https://orcid.org/0000-0002-1520-2268</a>)<br><strong>Last modified:</strong> NA<br><strong>Compiled</strong>: Wed Oct 28 15:30:41 2020</p>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>This vignette demonstrates how the handle and process proteomics identification data using the <code>PSM</code> package and general handling packages such <code>dplyr</code>.</p>
</div>
<div id="handling-and-processing-identification-data" class="section level1">
<h1 class="hasAnchor">
<a href="#handling-and-processing-identification-data" class="anchor"></a>Handling and processing identification data</h1>
<div id="loading-psm-data" class="section level2">
<h2 class="hasAnchor">
<a href="#loading-psm-data" class="anchor"></a>Loading PSM data</h2>
<p>We are going to use an <code>mzid</code> file from the <code>msdata</code> package.</p>
<div class="sourceCode" id="cb1"><pre class="downlit">
<span class="va">f</span> <span class="op">&lt;-</span> <span class="fu">msdata</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/msdata/man/proteomics.html">ident</a></span><span class="op">(</span>full.names <span class="op">=</span> <span class="cn">TRUE</span>, pattern <span class="op">=</span> <span class="st">"TMT"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></pre></div>
<pre><code>## [1] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid"</code></pre>
<p>The <code><a href="../reference/readPSMs.html">readPSMs()</a></code> function parses one of multiple <code>mzid</code> files and returns an object of class <code>DFrame</code>.</p>
<div class="sourceCode" id="cb3"><pre class="downlit">
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/RforMassSpectrometry/PSM">"PSM"</a></span><span class="op">)</span>
<span class="va">id</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/readPSMs.html">readPSMs</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></pre></div>
<pre><code>## Loading required namespace: mzR</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit">
<span class="va">id</span></pre></div>
<pre><code>## DataFrame with 5802 rows and 35 columns
##                    sequence             spectrumID chargeState      rank
##                 &lt;character&gt;            &lt;character&gt;   &lt;integer&gt; &lt;integer&gt;
## 1              RQCRTDFLNYLR controllerType=0 con..           3         1
## 2    ESVALADQVTCVDWRNRKATKK controllerType=0 con..           2         1
## 3              KELLCLAMQIIR controllerType=0 con..           2         1
## 4    QRMARTSDKQQSIRFLERLCGR controllerType=0 con..           3         1
## 5    KDEGSTEPLKVVRDMTDAIC.. controllerType=0 con..           3         1
## ...                     ...                    ...         ...       ...
## 5798              LLLARLFLK controllerType=0 con..           2         1
## 5799                LFSLLKK controllerType=0 con..           2         1
## 5800              LAATKKITK controllerType=0 con..           2         1
## 5801               RLIPVVKR controllerType=0 con..           2         1
## 5802                 IVKFRR controllerType=0 con..           2         1
##      passThreshold experimentalMassToCharge calculatedMassToCharge  peptideRef
##          &lt;logical&gt;                &lt;numeric&gt;              &lt;numeric&gt; &lt;character&gt;
## 1             TRUE                  548.286                547.947       Pep77
## 2             TRUE                 1288.153               1288.174      Pep108
## 3             TRUE                  744.411                744.425      Pep136
## 4             TRUE                  913.164                912.813      Pep163
## 5             TRUE                  926.810                926.471      Pep169
## ...            ...                      ...                    ...         ...
## 5798          TRUE                  543.874                543.874     Pep4927
## 5799          TRUE                  425.290                424.784     Pep4842
## 5800          TRUE                  487.834                487.324     Pep4891
## 5801          TRUE                  491.343                490.840     Pep4885
## 5802          TRUE                  410.281                409.772     Pep4861
##         modNum   isDecoy        post         pre     start       end
##      &lt;integer&gt; &lt;logical&gt; &lt;character&gt; &lt;character&gt; &lt;integer&gt; &lt;integer&gt;
## 1            1     FALSE           V           R       574       585
## 2            1     FALSE           G           R        69        90
## 3            1      TRUE           Q           R       131       142
## 4            1     FALSE           D           R       182       203
## 5            1      TRUE           R           R       135       158
## ...        ...       ...         ...         ...       ...       ...
## 5798         0     FALSE           P           R       449       457
## 5799         0     FALSE           R           R        40        46
## 5800         0     FALSE           -           R       312       320
## 5801         0      TRUE           G           K       160       167
## 5802         0     FALSE           R           K        74        79
##      DatabaseAccess DBseqLength DatabaseSeq    DatabaseDescription
##         &lt;character&gt;   &lt;integer&gt; &lt;character&gt;            &lt;character&gt;
## 1           ECA2006        1295             ECA2006 ATP-dependen..
## 2           ECA1676         110             ECA1676 putative gro..
## 3       XXX_ECA2855         157                                   
## 4           ECA3009         437             ECA3009 putative cop..
## 5       XXX_ECA0048         501                                   
## ...             ...         ...         ...                    ...
## 5798        ECA2534         636             ECA2534 ABC transpor..
## 5799        ECA1583          83             ECA1583 putative int..
## 5800        ECA0610         320             ECA0610 LysR-family ..
## 5801    XXX_ECA3377         211                                   
## 5802        ECA0690         103             ECA0690 50S ribosoma..
##      scan.number.s. acquisitionNum           spectrumFile
##           &lt;numeric&gt;      &lt;numeric&gt;            &lt;character&gt;
## 1              2949           2949 TMT_Erwinia_1uLSike_..
## 2              6534           6534 TMT_Erwinia_1uLSike_..
## 3              5674           5674 TMT_Erwinia_1uLSike_..
## 4              4782           4782 TMT_Erwinia_1uLSike_..
## 5              5839           5839 TMT_Erwinia_1uLSike_..
## ...             ...            ...                    ...
## 5798           2533           2533 TMT_Erwinia_1uLSike_..
## 5799           2645           2645 TMT_Erwinia_1uLSike_..
## 5800           1699           1699 TMT_Erwinia_1uLSike_..
## 5801           6739           6739 TMT_Erwinia_1uLSike_..
## 5802           1634           1634 TMT_Erwinia_1uLSike_..
##                      idFile MS.GF.RawScore MS.GF.DeNovoScore MS.GF.SpecEValue
##                 &lt;character&gt;      &lt;numeric&gt;         &lt;numeric&gt;        &lt;numeric&gt;
## 1    TMT_Erwinia_1uLSike_..             10               101      4.61712e-08
## 2    TMT_Erwinia_1uLSike_..             12               121      7.25588e-08
## 3    TMT_Erwinia_1uLSike_..              8                74      9.34102e-08
## 4    TMT_Erwinia_1uLSike_..             -5               160      1.27073e-07
## 5    TMT_Erwinia_1uLSike_..              8               241      1.31824e-07
## ...                     ...            ...               ...              ...
## 5798 TMT_Erwinia_1uLSike_..            -90               118      0.004498388
## 5799 TMT_Erwinia_1uLSike_..           -102                43      0.006621415
## 5800 TMT_Erwinia_1uLSike_..            -66                90      0.001297466
## 5801 TMT_Erwinia_1uLSike_..            -91                16      0.001965771
## 5802 TMT_Erwinia_1uLSike_..            -44                54      0.000919113
##      MS.GF.EValue MS.GF.QValue MS.GF.PepQValue modPeptideRef         modName
##         &lt;numeric&gt;    &lt;numeric&gt;       &lt;numeric&gt;   &lt;character&gt;     &lt;character&gt;
## 1        0.132198     0.525424        0.549020         Pep77 Carbamidomethyl
## 2        0.208748     0.610390        0.623188        Pep108 Carbamidomethyl
## 3        0.267453     0.625000        0.636364        Pep136 Carbamidomethyl
## 4        0.365583     0.716981        0.724490        Pep163 Carbamidomethyl
## 5        0.379461     0.736364        0.745098        Pep169 Carbamidomethyl
## ...           ...          ...             ...           ...             ...
## 5798     12838.72            1               1            NA              NA
## 5799     18816.18            1               1            NA              NA
## 5800      3703.06            1               1            NA              NA
## 5801      5600.99            1               1            NA              NA
## 5802      2587.26            1               1            NA              NA
##        modMass modLocation subOriginalResidue subReplacementResidue subLocation
##      &lt;numeric&gt;   &lt;integer&gt;        &lt;character&gt;           &lt;character&gt;   &lt;integer&gt;
## 1      57.0215           3                 NA                    NA          NA
## 2      57.0215          11                 NA                    NA          NA
## 3      57.0215           5                 NA                    NA          NA
## 4      57.0215          20                 NA                    NA          NA
## 5      57.0215          20                 NA                    NA          NA
## ...        ...         ...                ...                   ...         ...
## 5798        NA          NA                 NA                    NA          NA
## 5799        NA          NA                 NA                    NA          NA
## 5800        NA          NA                 NA                    NA          NA
## 5801        NA          NA                 NA                    NA          NA
## 5802        NA          NA                 NA                    NA          NA</code></pre>
<p>This table contains 5802 matches for 5343 scans and 4938 peptides sequences.</p>
<div class="sourceCode" id="cb7"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span> <span class="co">## number of matches</span></pre></div>
<pre><code>## [1] 5802</code></pre>
<div class="sourceCode" id="cb9"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span> <span class="co">## number of scans</span></pre></div>
<pre><code>## [1] 5343</code></pre>
<div class="sourceCode" id="cb11"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">sequence</span><span class="op">)</span><span class="op">)</span>   <span class="co">## number of peptide sequences</span></pre></div>
<pre><code>## [1] 4938</code></pre>
<p>The PSM data are read as is, without and filtering. As we can see below, we still have all the hits from the forward and reverse (decoy) databases.</p>
<div class="sourceCode" id="cb13"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">isDecoy</span><span class="op">)</span></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2906  2896</code></pre>
</div>
<div id="keeping-all-matches" class="section level2">
<h2 class="hasAnchor">
<a href="#keeping-all-matches" class="anchor"></a>Keeping all matches</h2>
<p>The data contains also contains multiple matches for several spectra. The table below shows the number of number of spectra that have 1, 2, … up to 5 matches.</p>
<div class="sourceCode" id="cb15"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## 
##    1    2    3    4    5 
## 4936  369   26   10    2</code></pre>
<p>Below, we can see how scan 1774 has 4 matches, all to sequence <code>RTRYQAEVR</code>, which itself matches to 4 different proteins:</p>
<div class="sourceCode" id="cb17"><pre class="downlit">
<span class="va">i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="st">"controllerType=0 controllerNumber=1 scan=1774"</span><span class="op">)</span>
<span class="va">id</span><span class="op">[</span><span class="va">i</span>, <span class="op">]</span></pre></div>
<pre><code>## DataFrame with 4 rows and 35 columns
##      sequence             spectrumID chargeState      rank passThreshold
##   &lt;character&gt;            &lt;character&gt;   &lt;integer&gt; &lt;integer&gt;     &lt;logical&gt;
## 1   RTRYQAEVR controllerType=0 con..           2         1          TRUE
## 2   RTRYQAEVR controllerType=0 con..           2         1          TRUE
## 3   RTRYQAEVR controllerType=0 con..           2         1          TRUE
## 4   RTRYQAEVR controllerType=0 con..           2         1          TRUE
##   experimentalMassToCharge calculatedMassToCharge  peptideRef    modNum
##                  &lt;numeric&gt;              &lt;numeric&gt; &lt;character&gt; &lt;integer&gt;
## 1                  589.821                589.823     Pep1890         0
## 2                  589.821                589.823     Pep1890         0
## 3                  589.821                589.823     Pep1890         0
## 4                  589.821                589.823     Pep1890         0
##     isDecoy        post         pre     start       end DatabaseAccess
##   &lt;logical&gt; &lt;character&gt; &lt;character&gt; &lt;integer&gt; &lt;integer&gt;    &lt;character&gt;
## 1     FALSE           P           R        89        97        ECA2104
## 2     FALSE           P           R        99       107        ECA2867
## 3     FALSE           P           R        89        97        ECA3427
## 4     FALSE           P           R        89        97        ECA4142
##   DBseqLength DatabaseSeq    DatabaseDescription scan.number.s. acquisitionNum
##     &lt;integer&gt; &lt;character&gt;            &lt;character&gt;      &lt;numeric&gt;      &lt;numeric&gt;
## 1         675               ECA2104 VgrG protein           1774           1774
## 2         619             ECA2867 putative RHS..           1774           1774
## 3         678             ECA3427 conserved hy..           1774           1774
## 4         675               ECA4142 VgrG protein           1774           1774
##             spectrumFile                 idFile MS.GF.RawScore
##              &lt;character&gt;            &lt;character&gt;      &lt;numeric&gt;
## 1 TMT_Erwinia_1uLSike_.. TMT_Erwinia_1uLSike_..              0
## 2 TMT_Erwinia_1uLSike_.. TMT_Erwinia_1uLSike_..              0
## 3 TMT_Erwinia_1uLSike_.. TMT_Erwinia_1uLSike_..              0
## 4 TMT_Erwinia_1uLSike_.. TMT_Erwinia_1uLSike_..              0
##   MS.GF.DeNovoScore MS.GF.SpecEValue MS.GF.EValue MS.GF.QValue MS.GF.PepQValue
##           &lt;numeric&gt;        &lt;numeric&gt;    &lt;numeric&gt;    &lt;numeric&gt;       &lt;numeric&gt;
## 1                96      3.69254e-06      10.5388            1        0.990816
## 2                96      3.69254e-06      10.5388            1        0.990816
## 3                96      3.69254e-06      10.5388            1        0.990816
## 4                96      3.69254e-06      10.5388            1        0.990816
##   modPeptideRef     modName   modMass modLocation subOriginalResidue
##     &lt;character&gt; &lt;character&gt; &lt;numeric&gt;   &lt;integer&gt;        &lt;character&gt;
## 1            NA          NA        NA          NA                 NA
## 2            NA          NA        NA          NA                 NA
## 3            NA          NA        NA          NA                 NA
## 4            NA          NA        NA          NA                 NA
##   subReplacementResidue subLocation
##             &lt;character&gt;   &lt;integer&gt;
## 1                    NA          NA
## 2                    NA          NA
## 3                    NA          NA
## 4                    NA          NA</code></pre>
<p>If the goal is to keep all the matches, but arranged by scan/spectrum, one can <em>reduce</em> the <code>DataFrame</code> object by the <code>spectrumID</code> variable, so that each scal correponds to a single row that still stores all values<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>:</p>
<div class="sourceCode" id="cb19"><pre class="downlit">
<span class="va">id2</span> <span class="op">&lt;-</span> <span class="fu">QFeatures</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/QFeatures/man/reduceDataFrame.html">reduceDataFrame</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co">## rownames not needed here</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></pre></div>
<pre><code>## [1] 5343   35</code></pre>
<p>The resulting object contains a single entrie for scan 1774 with information for the multiple matches stored as lists within the cells.</p>
<div class="sourceCode" id="cb21"><pre class="downlit">
<span class="va">j</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">id2</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="st">"controllerType=0 controllerNumber=1 scan=1774"</span><span class="op">)</span>
<span class="va">id2</span><span class="op">[</span><span class="va">j</span>, <span class="op">]</span></pre></div>
<pre><code>## DataFrame with 1 row and 35 columns
##                            sequence    spectrumID chargeState          rank
##                     &lt;CharacterList&gt;   &lt;character&gt;   &lt;integer&gt; &lt;IntegerList&gt;
## 1 RTRYQAEVR,RTRYQAEVR,RTRYQAEVR,... controller...           2     1,1,1,...
##   passThreshold experimentalMassToCharge      calculatedMassToCharge
##       &lt;logical&gt;                &lt;numeric&gt;               &lt;NumericList&gt;
## 1          TRUE                  589.821 589.823,589.823,589.823,...
##                    peptideRef        modNum               isDecoy
##               &lt;CharacterList&gt; &lt;IntegerList&gt;         &lt;LogicalList&gt;
## 1 Pep1890,Pep1890,Pep1890,...     0,0,0,... FALSE,FALSE,FALSE,...
##              post             pre         start           end
##   &lt;CharacterList&gt; &lt;CharacterList&gt; &lt;IntegerList&gt; &lt;IntegerList&gt;
## 1       P,P,P,...       R,R,R,...  89,99,89,... 97,107,97,...
##                DatabaseAccess     DBseqLength DatabaseSeq
##               &lt;CharacterList&gt;   &lt;IntegerList&gt; &lt;character&gt;
## 1 ECA2104,ECA2867,ECA3427,... 675,619,678,...            
##                             DatabaseDescription scan.number.s. acquisitionNum
##                                 &lt;CharacterList&gt;      &lt;numeric&gt;      &lt;numeric&gt;
## 1 ECA2104 Vg...,ECA2867 pu...,ECA3427 co...,...           1774           1774
##    spectrumFile        idFile MS.GF.RawScore MS.GF.DeNovoScore MS.GF.SpecEValue
##     &lt;character&gt;   &lt;character&gt;      &lt;numeric&gt;         &lt;numeric&gt;        &lt;numeric&gt;
## 1 TMT_Erwini... TMT_Erwini...              0                96      3.69254e-06
##                  MS.GF.EValue MS.GF.QValue                MS.GF.PepQValue
##                 &lt;NumericList&gt;    &lt;numeric&gt;                  &lt;NumericList&gt;
## 1 10.5388,10.5388,10.5388,...            1 0.990816,0.990816,0.990816,...
##     modPeptideRef         modName       modMass   modLocation
##   &lt;CharacterList&gt; &lt;CharacterList&gt; &lt;NumericList&gt; &lt;IntegerList&gt;
## 1    NA,NA,NA,...    NA,NA,NA,...  NA,NA,NA,...  NA,NA,NA,...
##   subOriginalResidue subReplacementResidue subLocation
##          &lt;character&gt;           &lt;character&gt;   &lt;integer&gt;
## 1                 NA                    NA          NA</code></pre>
<div class="sourceCode" id="cb23"><pre class="downlit">
<span class="va">id2</span><span class="op">[</span><span class="va">j</span>, <span class="st">"DatabaseAccess"</span><span class="op">]</span></pre></div>
<pre><code>## CharacterList of length 1
## [["controllerType=0 controllerNumber=1 scan=1774"]] ECA2104 ECA2867 ECA3427 ECA4142</code></pre>
<p>The is the type of complete identification table that could be used to annotate an raw mass spectrometry <code>Spectra</code> object.</p>
</div>
<div id="filtering-data" class="section level2">
<h2 class="hasAnchor">
<a href="#filtering-data" class="anchor"></a>Filtering data</h2>
<p>Often, the PSM data is filtered to only retain reliable matches. The <code>MSnID</code> package can be used to set thresholds to attain user-defined PSM, peptide or protein-level FDRs. Here, we will simply filter out wrong identification manually.</p>
<p>Here, the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> from the <code>dplyr</code> package comes very handy. We will thus start by convering the <code>DataFrame</code> to a <code>tibble</code>.</p>
<div class="sourceCode" id="cb25"><pre class="downlit">
<span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span>
<span class="va">id_tbl</span></pre></div>
<pre><code>## # A tibble: 5,802 x 35
##    sequence spectrumID chargeState  rank passThreshold experimentalMas…
##    &lt;chr&gt;    &lt;chr&gt;            &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                    &lt;dbl&gt;
##  1 RQCRTDF… controlle…           3     1 TRUE                      548.
##  2 ESVALAD… controlle…           2     1 TRUE                     1288.
##  3 KELLCLA… controlle…           2     1 TRUE                      744.
##  4 QRMARTS… controlle…           3     1 TRUE                      913.
##  5 KDEGSTE… controlle…           3     1 TRUE                      927.
##  6 DGGPAIY… controlle…           3     1 TRUE                      969.
##  7 QRMARTS… controlle…           2     1 TRUE                     1369.
##  8 CIDRARH… controlle…           3     1 TRUE                     1285.
##  9 CIDRARH… controlle…           3     1 TRUE                     1285.
## 10 VGRCRPI… controlle…           2     1 TRUE                     1102.
## # … with 5,792 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
<div id="remove-decoy-hits" class="section level3">
<h3 class="hasAnchor">
<a href="#remove-decoy-hits" class="anchor"></a>Remove decoy hits</h3>
<div class="sourceCode" id="cb27"><pre class="downlit">
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://dplyr.tidyverse.org">"dplyr"</a></span><span class="op">)</span>
<span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="va">isDecoy</span><span class="op">)</span>
<span class="va">id_tbl</span></pre></div>
<pre><code>## # A tibble: 2,906 x 35
##    sequence spectrumID chargeState  rank passThreshold experimentalMas…
##    &lt;chr&gt;    &lt;chr&gt;            &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                    &lt;dbl&gt;
##  1 RQCRTDF… controlle…           3     1 TRUE                      548.
##  2 ESVALAD… controlle…           2     1 TRUE                     1288.
##  3 QRMARTS… controlle…           3     1 TRUE                      913.
##  4 DGGPAIY… controlle…           3     1 TRUE                      969.
##  5 QRMARTS… controlle…           2     1 TRUE                     1369.
##  6 CIDRARH… controlle…           3     1 TRUE                     1285.
##  7 CIDRARH… controlle…           3     1 TRUE                     1285.
##  8 VGRCRPI… controlle…           2     1 TRUE                     1102.
##  9 QRLDEHC… controlle…           3     1 TRUE                      713.
## 10 VDYQGKK… controlle…           4     1 TRUE                      870.
## # … with 2,896 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
</div>
<div id="keep-first-rank-matches" class="section level3">
<h3 class="hasAnchor">
<a href="#keep-first-rank-matches" class="anchor"></a>Keep first rank matches</h3>
<div class="sourceCode" id="cb29"><pre class="downlit">
<span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rank</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">id_tbl</span></pre></div>
<pre><code>## # A tibble: 2,751 x 35
##    sequence spectrumID chargeState  rank passThreshold experimentalMas…
##    &lt;chr&gt;    &lt;chr&gt;            &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                    &lt;dbl&gt;
##  1 RQCRTDF… controlle…           3     1 TRUE                      548.
##  2 ESVALAD… controlle…           2     1 TRUE                     1288.
##  3 QRMARTS… controlle…           3     1 TRUE                      913.
##  4 DGGPAIY… controlle…           3     1 TRUE                      969.
##  5 QRMARTS… controlle…           2     1 TRUE                     1369.
##  6 CIDRARH… controlle…           3     1 TRUE                     1285.
##  7 CIDRARH… controlle…           3     1 TRUE                     1285.
##  8 VGRCRPI… controlle…           2     1 TRUE                     1102.
##  9 QRLDEHC… controlle…           3     1 TRUE                      713.
## 10 VDYQGKK… controlle…           4     1 TRUE                      870.
## # … with 2,741 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
</div>
<div id="remove-non-proteotypic-peptides" class="section level3">
<h3 class="hasAnchor">
<a href="#remove-non-proteotypic-peptides" class="anchor"></a>Remove non-proteotypic peptides</h3>
<p>The scans below are those that match different proteins. For example scan 4884 (the two first rows) matches proteins <code>XXX_ECA3406</code> and <code>ECA3415</code>. Scan 4099 (rows 6 to 8) match <code>XXX_ECA4416_1</code>, <code>XXX_ECA4416_2</code> and <code>XXX_ECA4416_3</code>.</p>
<div class="sourceCode" id="cb31"><pre class="downlit">
<span class="va">mltm</span> <span class="op">&lt;-</span>
    <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">spectrumID</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>nProts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">DatabaseAccess</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">nProts</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">DatabaseAccess</span>, <span class="va">nProts</span><span class="op">)</span></pre></div>
<pre><code>## Adding missing grouping variables: `spectrumID`</code></pre>
<div class="sourceCode" id="cb33"><pre class="downlit">
<span class="va">mltm</span></pre></div>
<pre><code>## # A tibble: 85 x 3
## # Groups:   spectrumID [39]
##    spectrumID                                    DatabaseAccess nProts
##    &lt;chr&gt;                                         &lt;chr&gt;           &lt;int&gt;
##  1 controllerType=0 controllerNumber=1 scan=1073 ECA2869             2
##  2 controllerType=0 controllerNumber=1 scan=1073 ECA4278             2
##  3 controllerType=0 controllerNumber=1 scan=6578 ECA3480             2
##  4 controllerType=0 controllerNumber=1 scan=6578 ECA3481             2
##  5 controllerType=0 controllerNumber=1 scan=5617 ECA4283             2
##  6 controllerType=0 controllerNumber=1 scan=5617 ECA4292             2
##  7 controllerType=0 controllerNumber=1 scan=3926 ECA0216             2
##  8 controllerType=0 controllerNumber=1 scan=3926 ECA4035             2
##  9 controllerType=0 controllerNumber=1 scan=4784 ECA0216             2
## 10 controllerType=0 controllerNumber=1 scan=4784 ECA4035             2
## # … with 75 more rows</code></pre>
<p>We can now remove the scane with</p>
<div class="sourceCode" id="cb35"><pre class="downlit">
<span class="va">id_tbl</span> <span class="op">&lt;-</span>
    <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="va">spectrumID</span> <span class="op">%in%</span> <span class="va">mltm</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span>
<span class="va">id_tbl</span></pre></div>
<pre><code>## # A tibble: 2,666 x 35
##    sequence spectrumID chargeState  rank passThreshold experimentalMas…
##    &lt;chr&gt;    &lt;chr&gt;            &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                    &lt;dbl&gt;
##  1 RQCRTDF… controlle…           3     1 TRUE                      548.
##  2 ESVALAD… controlle…           2     1 TRUE                     1288.
##  3 QRMARTS… controlle…           3     1 TRUE                      913.
##  4 DGGPAIY… controlle…           3     1 TRUE                      969.
##  5 QRMARTS… controlle…           2     1 TRUE                     1369.
##  6 CIDRARH… controlle…           3     1 TRUE                     1285.
##  7 CIDRARH… controlle…           3     1 TRUE                     1285.
##  8 VGRCRPI… controlle…           2     1 TRUE                     1102.
##  9 QRLDEHC… controlle…           3     1 TRUE                      713.
## 10 VDYQGKK… controlle…           4     1 TRUE                      870.
## # … with 2,656 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
<p>Which leaves us with 2666 PSMs.</p>
<p>This can also be achieved with the <code><a href="../reference/filterPSMs.html">filterPSMs()</a></code> function:</p>
<div class="sourceCode" id="cb37"><pre class="downlit">
<span class="va">id_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span></pre></div>
<pre><code>## Starting with 5802 PSMs:</code></pre>
<pre><code>##  removed 2896 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2666 PSMs left.</code></pre>
</div>
</div>
</div>
<div id="the-mzr-and-mzid-parsers" class="section level1">
<h1 class="hasAnchor">
<a href="#the-mzr-and-mzid-parsers" class="anchor"></a>The <code>mzR</code> and <code>mzID</code> parsers</h1>
<p>The <code><a href="../reference/readPSMs.html">readPSMs()</a></code> function can take two different values for the <code>parser</code> parameter, namely <code>"mzR"</code> (which is also the default value) and <code>"mzID"</code>.</p>
<ul>
<li><p><strong>mzR</strong> uses the <code><a href="https://rdrr.io/pkg/mzR/man/openMSfile.html">openIDfile()</a></code> function from the <em><a href="https://bioconductor.org/packages/3.12/mzR">mzR</a></em> to parse the <code>mzId</code> file(s), and then coerces the data to a <code>data.frame</code> which is eventually returned as a <code>DataFrame</code>. The parser function uses dedicated code from the Proteowizard project (included in <code>mzR</code>) and is generally the fastest approach.</p></li>
<li><p><strong>mzID</strong> parses the <code>mzId</code> file with <code>mzID()</code> function from the <em><a href="https://bioconductor.org/packages/3.12/mzID">mzID</a></em> package, and the flattens the data to a <code>data.frame</code> with <code><a href="https://rdrr.io/pkg/mzID/man/flatten.html">mzID::flatten()</a></code> and eventuelly returns a <code>DataFrame</code>. The <code>mzID</code> package relies on the <em><a href="https://CRAN.R-project.org/package=XML">XML</a></em> package. Is is slower but is is more robust to variations in the <code>mzID</code> implementation, as is a useful backup when the <code>mzR</code> approach fails with errors.</p></li>
</ul>
<div class="sourceCode" id="cb43"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/system.time.html">system.time</a></span><span class="op">(</span><span class="va">id1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/readPSMs.html">readPSMs</a></span><span class="op">(</span><span class="va">f</span>, parser <span class="op">=</span> <span class="st">"mzR"</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>##    user  system elapsed 
##   0.229   0.000   0.230</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/system.time.html">system.time</a></span><span class="op">(</span><span class="va">id2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/readPSMs.html">readPSMs</a></span><span class="op">(</span><span class="va">f</span>, parser <span class="op">=</span> <span class="st">"mzID"</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## Loading required namespace: mzID</code></pre>
<pre><code>## reading TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid... DONE!</code></pre>
<pre><code>##    user  system elapsed 
##   7.639   0.068   7.707</code></pre>
<p>Other differences in the two parsers include the columns that are returned, way they name them, and, as will shown below the matches that are returned. Below, note for instance (and this will be important later), that there is not equivalent of <code>"modLocation"</code> in <code>id2</code>.</p>
<div class="sourceCode" id="cb49"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></pre></div>
<pre><code>##  [1] "sequence"                 "spectrumID"              
##  [3] "chargeState"              "rank"                    
##  [5] "passThreshold"            "experimentalMassToCharge"
##  [7] "calculatedMassToCharge"   "peptideRef"              
##  [9] "modNum"                   "isDecoy"                 
## [11] "post"                     "pre"                     
## [13] "start"                    "end"                     
## [15] "DatabaseAccess"           "DBseqLength"             
## [17] "DatabaseSeq"              "DatabaseDescription"     
## [19] "scan.number.s."           "acquisitionNum"          
## [21] "spectrumFile"             "idFile"                  
## [23] "MS.GF.RawScore"           "MS.GF.DeNovoScore"       
## [25] "MS.GF.SpecEValue"         "MS.GF.EValue"            
## [27] "MS.GF.QValue"             "MS.GF.PepQValue"         
## [29] "modPeptideRef"            "modName"                 
## [31] "modMass"                  "modLocation"             
## [33] "subOriginalResidue"       "subReplacementResidue"   
## [35] "subLocation"</code></pre>
<div class="sourceCode" id="cb51"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></pre></div>
<pre><code>##  [1] "spectrumid"                "scan number(s)"           
##  [3] "acquisitionnum"            "passthreshold"            
##  [5] "rank"                      "calculatedmasstocharge"   
##  [7] "experimentalmasstocharge"  "chargestate"              
##  [9] "ms-gf:denovoscore"         "ms-gf:evalue"             
## [11] "ms-gf:pepqvalue"           "ms-gf:qvalue"             
## [13] "ms-gf:rawscore"            "ms-gf:specevalue"         
## [15] "assumeddissociationmethod" "isotopeerror"             
## [17] "isdecoy"                   "post"                     
## [19] "pre"                       "end"                      
## [21] "start"                     "accession"                
## [23] "length"                    "description"              
## [25] "pepseq"                    "modified"                 
## [27] "modification"              "idFile"                   
## [29] "spectrumFile"              "databaseFile"</code></pre>
<p>We also have different number of matches in the two tables:</p>
<div class="sourceCode" id="cb53"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></pre></div>
<pre><code>## [1] 5802</code></pre>
<div class="sourceCode" id="cb55"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></pre></div>
<pre><code>## [1] 5759</code></pre>
<div class="sourceCode" id="cb57"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id1</span><span class="op">$</span><span class="va">isDecoy</span><span class="op">)</span></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2906  2896</code></pre>
<div class="sourceCode" id="cb59"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id2</span><span class="op">$</span><span class="va">isdecoy</span><span class="op">)</span></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2886  2873</code></pre>
<p>Let’s first filter the PSM tables to facilitate focus the comparison of relevant scans. Note that the default <code><a href="../reference/filterPSMs.html">filterPSMs()</a></code> arguments are set to work with the <code>mzR</code> parser.</p>
<div class="sourceCode" id="cb61"><pre class="downlit">
<span class="va">id1_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></pre></div>
<pre><code>## Starting with 5802 PSMs:</code></pre>
<pre><code>##  removed 2896 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2666 PSMs left.</code></pre>
<div class="sourceCode" id="cb67"><pre class="downlit">
<span class="va">id2_filtered</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id2</span>, decoy <span class="op">=</span> <span class="st">"isdecoy"</span>,
           accession <span class="op">=</span> <span class="st">"accession"</span>,
           spectrumID <span class="op">=</span> <span class="st">"spectrumid"</span><span class="op">)</span></pre></div>
<pre><code>## Starting with 5759 PSMs:</code></pre>
<pre><code>##  removed 2873 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2646 PSMs left.</code></pre>
<p>As can be seen, we are also left with 2666 vs 2646 PSMs after filtering.</p>
<p>The difference doesn’t stem from different scans, given that the spectum identifiers are identical in both tables:</p>
<div class="sourceCode" id="cb73"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span>,
          <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">id2_filtered</span><span class="op">$</span><span class="va">spectrumid</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>The difference is obvious when we tally a table of spectrum ids occurences in the filtered tables. In <code>id2_filtered</code>, each scan is unique, i.e matched only once.</p>
<div class="sourceCode" id="cb75"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">anyDuplicated</a></span><span class="op">(</span><span class="va">id2_filtered</span><span class="op">$</span><span class="va">spectrumid</span><span class="op">)</span></pre></div>
<pre><code>## [1] 0</code></pre>
<p>However, for <code>id1_filtered</code>, we see that some scans are still repeat up to 4 times in the table:</p>
<div class="sourceCode" id="cb77"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## 
##    1    2    3    4 
## 2630   13    2    1</code></pre>
<p>The example below shows that these differences stem from the modification location (<code>"modLocation"</code>), that is not report by the <code>mzID</code> parser:</p>
<div class="sourceCode" id="cb79"><pre class="downlit">
<span class="va">k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span> <span class="op">==</span> <span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">id1_filtered</span><span class="op">[</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="va">k</span>, <span class="op">]</span></pre></div>
<pre><code>## DataFrame with 4 rows and 35 columns
##        sequence    spectrumID chargeState      rank passThreshold
##     &lt;character&gt;   &lt;character&gt;   &lt;integer&gt; &lt;integer&gt;     &lt;logical&gt;
## 1 KCNQCLKVAC... controller...           3         1          TRUE
## 2 KCNQCLKVAC... controller...           3         1          TRUE
## 3 KCNQCLKVAC... controller...           3         1          TRUE
## 4 KCNQCLKVAC... controller...           3         1          TRUE
##   experimentalMassToCharge calculatedMassToCharge  peptideRef    modNum
##                  &lt;numeric&gt;              &lt;numeric&gt; &lt;character&gt; &lt;integer&gt;
## 1                  698.663                698.331      Pep453         4
## 2                  698.663                698.331      Pep453         4
## 3                  698.663                698.331      Pep453         4
## 4                  698.663                698.331      Pep453         4
##     isDecoy        post         pre     start       end DatabaseAccess
##   &lt;logical&gt; &lt;character&gt; &lt;character&gt; &lt;integer&gt; &lt;integer&gt;    &lt;character&gt;
## 1     FALSE           C           K       127       142        ECA0668
## 2     FALSE           C           K       127       142        ECA0668
## 3     FALSE           C           K       127       142        ECA0668
## 4     FALSE           C           K       127       142        ECA0668
##   DBseqLength DatabaseSeq DatabaseDescription scan.number.s. acquisitionNum
##     &lt;integer&gt; &lt;character&gt;         &lt;character&gt;      &lt;numeric&gt;      &lt;numeric&gt;
## 1         302                   ECA0668 hy...           5490           5490
## 2         302                   ECA0668 hy...           5490           5490
## 3         302                   ECA0668 hy...           5490           5490
## 4         302                   ECA0668 hy...           5490           5490
##    spectrumFile        idFile MS.GF.RawScore MS.GF.DeNovoScore MS.GF.SpecEValue
##     &lt;character&gt;   &lt;character&gt;      &lt;numeric&gt;         &lt;numeric&gt;        &lt;numeric&gt;
## 1 TMT_Erwini... TMT_Erwini...            -22                79      4.55559e-07
## 2 TMT_Erwini... TMT_Erwini...            -22                79      4.55559e-07
## 3 TMT_Erwini... TMT_Erwini...            -22                79      4.55559e-07
## 4 TMT_Erwini... TMT_Erwini...            -22                79      4.55559e-07
##   MS.GF.EValue MS.GF.QValue MS.GF.PepQValue modPeptideRef       modName
##      &lt;numeric&gt;    &lt;numeric&gt;       &lt;numeric&gt;   &lt;character&gt;   &lt;character&gt;
## 1      1.30769     0.900621         0.89011        Pep453 Carbamidom...
## 2      1.30769     0.900621         0.89011        Pep453 Carbamidom...
## 3      1.30769     0.900621         0.89011        Pep453 Carbamidom...
## 4      1.30769     0.900621         0.89011        Pep453 Carbamidom...
##     modMass modLocation subOriginalResidue subReplacementResidue subLocation
##   &lt;numeric&gt;   &lt;integer&gt;        &lt;character&gt;           &lt;character&gt;   &lt;integer&gt;
## 1   57.0215           2                 NA                    NA          NA
## 2   57.0215           5                 NA                    NA          NA
## 3   57.0215          10                 NA                    NA          NA
## 4   57.0215          15                 NA                    NA          NA</code></pre>
<p>If we remove the <code>"modLocation"</code> column, we recoved the same number of PSMs than with the <code>mzID</code> parser.</p>
<div class="sourceCode" id="cb81"><pre class="downlit">
<span class="va">id1_filtered</span><span class="op">$</span><span class="va">modLocation</span> <span class="op">&lt;-</span> <span class="cn">NULL</span>
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">)</span><span class="op">)</span></pre></div>
<pre><code>## [1] 2646</code></pre>
</div>
<div id="session-information" class="section level1">
<h1 class="hasAnchor">
<a href="#session-information" class="anchor"></a>Session information</h1>
<div class="sourceCode" id="cb83"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></pre></div>
<pre><code>## R version 4.0.3 Patched (2020-10-21 r79360)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.1 LTS
## 
## Matrix products: default
## BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
## [1] dplyr_1.0.2         PSM_0.1.0           S4Vectors_0.27.14  
## [4] BiocGenerics_0.35.4 BiocStyle_2.17.2   
## 
## loaded via a namespace (and not attached):
##  [1] MatrixGenerics_1.1.8         Biobase_2.49.1              
##  [3] tidyr_1.1.2                  foreach_1.5.0               
##  [5] assertthat_0.2.1             BiocManager_1.30.10         
##  [7] msdata_0.29.0                GenomeInfoDbData_1.2.4      
##  [9] yaml_2.2.1                   pillar_1.4.6                
## [11] backports_1.1.10             lattice_0.20-41             
## [13] glue_1.4.2                   digest_0.6.25               
## [15] GenomicRanges_1.41.6         XVector_0.29.3              
## [17] htmltools_0.5.0              Matrix_1.2-18               
## [19] plyr_1.8.6                   XML_3.99-0.5                
## [21] pkgconfig_2.0.3              bookdown_0.20               
## [23] zlibbioc_1.35.0              purrr_0.3.4                 
## [25] MultiAssayExperiment_1.15.11 tibble_3.0.4                
## [27] generics_0.0.2               AnnotationFilter_1.13.0     
## [29] IRanges_2.23.10              ellipsis_0.3.1              
## [31] SummarizedExperiment_1.19.9  lazyeval_0.2.2              
## [33] cli_2.1.0                    magrittr_1.5                
## [35] crayon_1.3.4                 memoise_1.1.0               
## [37] evaluate_0.14                fs_1.5.0                    
## [39] ncdf4_1.17                   fansi_0.4.1                 
## [41] doParallel_1.0.15            MASS_7.3-53                 
## [43] QFeatures_0.99.4             mzR_2.23.1                  
## [45] textshaping_0.1.2            tools_4.0.3                 
## [47] lifecycle_0.2.0              matrixStats_0.57.0          
## [49] stringr_1.4.0                DelayedArray_0.15.17        
## [51] compiler_4.0.3               pkgdown_1.6.1.9000          
## [53] GenomeInfoDb_1.25.11         mzID_1.27.0                 
## [55] systemfonts_0.3.2            rlang_0.4.8                 
## [57] grid_4.0.3                   RCurl_1.98-1.2              
## [59] iterators_1.0.12             MsCoreUtils_1.1.7           
## [61] bitops_1.0-6                 rmarkdown_2.4               
## [63] codetools_0.2-16             R6_2.4.1                    
## [65] knitr_1.30                   utf8_1.1.4                  
## [67] rprojroot_1.3-2              ragg_0.4.0                  
## [69] ProtGenerics_1.21.0          desc_1.2.0                  
## [71] stringi_1.5.3                Rcpp_1.0.5                  
## [73] vctrs_0.3.4                  tidyselect_1.1.0            
## [75] xfun_0.18</code></pre>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>The rownames aren’t needed here are are removed to reduce to output in the the next code chunk display parts of <code>id2</code>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Laurent Gatto.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.9000.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
