<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Working with PSM data • PSM</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Working with PSM data">
<meta property="og:description" content="PSM">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    

    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">PSM</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.3.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/PSM.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/RforMassSpectrometry/PSM/" class="external-link">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="PSM_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Working with PSM data</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/RforMassSpectrometry/PSM/blob/master/vignettes/PSM.Rmd" class="external-link"><code>vignettes/PSM.Rmd</code></a></small>
      <div class="hidden name"><code>PSM.Rmd</code></div>

    </div>

    
    
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  document.querySelector("h1").className = "title";
});
</script><script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  var links = document.links;  
  for (var i = 0, linksLength = links.length; i < linksLength; i++)
    if (links[i].hostname != window.location.hostname)
      links[i].target = '_blank';
});
</script><p><strong>Package</strong>: <em><a href="https://bioconductor.org/packages/3.13/PSM" class="external-link">PSM</a></em><br><strong>Authors</strong>: Laurent Gatto [aut, cre] (<a href="https://orcid.org/0000-0002-1520-2268" class="external-link uri">https://orcid.org/0000-0002-1520-2268</a>), Johannes Rainer [aut] (<a href="https://orcid.org/0000-0002-6977-7147" class="external-link uri">https://orcid.org/0000-0002-6977-7147</a>), Sebastian Gibb [aut]<br><strong>Last modified:</strong> 2021-03-27 06:47:17<br><strong>Compiled</strong>: Sat Mar 27 07:24:03 2021</p>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>This vignette demonstrates how the handle and process proteomics identification data using the <code>PSM</code> package and general handling packages such <code>dplyr</code>.</p>
</div>
<div id="handling-and-processing-identification-data" class="section level1">
<h1 class="hasAnchor">
<a href="#handling-and-processing-identification-data" class="anchor"></a>Handling and processing identification data</h1>
<div id="loading-psm-data" class="section level2">
<h2 class="hasAnchor">
<a href="#loading-psm-data" class="anchor"></a>Loading PSM data</h2>
<p>We are going to use an <code>mzid</code> file from the <code>msdata</code> package.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">f</span> <span class="op">&lt;-</span> <span class="fu">msdata</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/msdata/man/proteomics.html" class="external-link">ident</a></span><span class="op">(</span>full.names <span class="op">=</span> <span class="cn">TRUE</span>, pattern <span class="op">=</span> <span class="st">"TMT"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/basename.html" class="external-link">basename</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid"</code></pre>
<p>The <code><a href="../reference/PSM.html">readPSMs()</a></code> function parses one of multiple <code>mzid</code> files and returns an object of class <code>DFrame</code>.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/RforMassSpectrometry/PSM" class="external-link">"PSM"</a></span><span class="op">)</span>
<span class="va">id</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/PSM.html">PSM</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></code></pre></div>
<pre><code>## Loading required namespace: mzR</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id</span></code></pre></div>
<pre><code>## PSM with 5802 rows and 35 columns.
## names(35): sequence spectrumID ... subReplacementResidue subLocation</code></pre>
<p>This table contains 5802 matches for 5343 scans and 4938 peptides sequences.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span> <span class="co">## number of matches</span></code></pre></div>
<pre><code>## [1] 5802</code></pre>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span> <span class="co">## number of scans</span></code></pre></div>
<pre><code>## [1] 5343</code></pre>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">sequence</span><span class="op">)</span><span class="op">)</span>   <span class="co">## number of peptide sequences</span></code></pre></div>
<pre><code>## [1] 4938</code></pre>
<p>The PSM data are read as is, without and filtering. As we can see below, we still have all the hits from the forward and reverse (decoy) databases.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">isDecoy</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2906  2896</code></pre>
</div>
<div id="keeping-all-matches" class="section level2">
<h2 class="hasAnchor">
<a href="#keeping-all-matches" class="anchor"></a>Keeping all matches</h2>
<p>The data contains also contains multiple matches for several spectra. The table below shows the number of number of spectra that have 1, 2, … up to 5 matches.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##    1    2    3    4    5 
## 4936  369   26   10    2</code></pre>
<p>Below, we can see how scan 1774 has 4 matches, all to sequence <code>RTRYQAEVR</code>, which itself matches to 4 different proteins:</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html" class="external-link">which</a></span><span class="op">(</span><span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="st">"controllerType=0 controllerNumber=1 scan=1774"</span><span class="op">)</span>
<span class="va">id</span><span class="op">[</span><span class="va">i</span>, <span class="op">]</span></code></pre></div>
<pre><code>## PSM with 4 rows and 35 columns.
## names(35): sequence spectrumID ... subReplacementResidue subLocation</code></pre>
<p>If the goal is to keep all the matches, but arranged by scan/spectrum, one can <em>reduce</em> the <code>DataFrame</code> object by the <code>spectrumID</code> variable, so that each scan correponds to a single row that still stores all values<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>:</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/PSM.html">reducePSMs</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">id</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co">## rownames not needed here</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 5343   35</code></pre>
<p>The resulting object contains a single entrie for scan 1774 with information for the multiple matches stored as lists within the cells.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">j</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html" class="external-link">which</a></span><span class="op">(</span><span class="va">id2</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="st">"controllerType=0 controllerNumber=1 scan=1774"</span><span class="op">)</span>
<span class="va">id2</span><span class="op">[</span><span class="va">j</span>, <span class="op">]</span></code></pre></div>
<pre><code>## Reduced PSM with 1 rows and 35 columns.
## names(35): sequence spectrumID ... subReplacementResidue subLocation</code></pre>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id2</span><span class="op">[</span><span class="va">j</span>, <span class="st">"DatabaseAccess"</span><span class="op">]</span></code></pre></div>
<pre><code>## CharacterList of length 1
## [["controllerType=0 controllerNumber=1 scan=1774"]] ECA2104 ECA2867 ECA3427 ECA4142</code></pre>
<p>The is the type of complete identification table that could be used to annotate an raw mass spectrometry <code>Spectra</code> object.</p>
</div>
<div id="filtering-data" class="section level2">
<h2 class="hasAnchor">
<a href="#filtering-data" class="anchor"></a>Filtering data</h2>
<p>Often, the PSM data is filtered to only retain reliable matches. The <code>MSnID</code> package can be used to set thresholds to attain user-defined PSM, peptide or protein-level FDRs. Here, we will simply filter out wrong identification manually.</p>
<p>Here, the <code><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter()</a></code> from the <code>dplyr</code> package comes very handy. We will thus start by convering the <code>DataFrame</code> to a <code>tibble</code>.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html" class="external-link">as_tibble</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span>
<span class="va">id_tbl</span></code></pre></div>
<pre><code>## # A tibble: 5,802 x 35
##    sequence     spectrumID     chargeState  rank passThreshold experimentalMass…
##    &lt;chr&gt;        &lt;chr&gt;                &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                     &lt;dbl&gt;
##  1 RQCRTDFLNYLR controllerTyp…           3     1 TRUE                       548.
##  2 ESVALADQVTC… controllerTyp…           2     1 TRUE                      1288.
##  3 KELLCLAMQIIR controllerTyp…           2     1 TRUE                       744.
##  4 QRMARTSDKQQ… controllerTyp…           3     1 TRUE                       913.
##  5 KDEGSTEPLKV… controllerTyp…           3     1 TRUE                       927.
##  6 DGGPAIYGHER… controllerTyp…           3     1 TRUE                       969.
##  7 QRMARTSDKQQ… controllerTyp…           2     1 TRUE                      1369.
##  8 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  9 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
## 10 VGRCRPIINYL… controllerTyp…           2     1 TRUE                      1102.
## # … with 5,792 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
<div id="remove-decoy-hits" class="section level3">
<h3 class="hasAnchor">
<a href="#remove-decoy-hits" class="anchor"></a>Remove decoy hits</h3>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://dplyr.tidyverse.org" class="external-link">"dplyr"</a></span><span class="op">)</span>
<span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="op">!</span><span class="va">isDecoy</span><span class="op">)</span>
<span class="va">id_tbl</span></code></pre></div>
<pre><code>## # A tibble: 2,906 x 35
##    sequence     spectrumID     chargeState  rank passThreshold experimentalMass…
##    &lt;chr&gt;        &lt;chr&gt;                &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                     &lt;dbl&gt;
##  1 RQCRTDFLNYLR controllerTyp…           3     1 TRUE                       548.
##  2 ESVALADQVTC… controllerTyp…           2     1 TRUE                      1288.
##  3 QRMARTSDKQQ… controllerTyp…           3     1 TRUE                       913.
##  4 DGGPAIYGHER… controllerTyp…           3     1 TRUE                       969.
##  5 QRMARTSDKQQ… controllerTyp…           2     1 TRUE                      1369.
##  6 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  7 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  8 VGRCRPIINYL… controllerTyp…           2     1 TRUE                      1102.
##  9 QRLDEHCVGVG… controllerTyp…           3     1 TRUE                       713.
## 10 VDYQGKKVVII… controllerTyp…           4     1 TRUE                       870.
## # … with 2,896 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
</div>
<div id="keep-first-rank-matches" class="section level3">
<h3 class="hasAnchor">
<a href="#keep-first-rank-matches" class="anchor"></a>Keep first rank matches</h3>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id_tbl</span> <span class="op">&lt;-</span> <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">rank</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">id_tbl</span></code></pre></div>
<pre><code>## # A tibble: 2,751 x 35
##    sequence     spectrumID     chargeState  rank passThreshold experimentalMass…
##    &lt;chr&gt;        &lt;chr&gt;                &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                     &lt;dbl&gt;
##  1 RQCRTDFLNYLR controllerTyp…           3     1 TRUE                       548.
##  2 ESVALADQVTC… controllerTyp…           2     1 TRUE                      1288.
##  3 QRMARTSDKQQ… controllerTyp…           3     1 TRUE                       913.
##  4 DGGPAIYGHER… controllerTyp…           3     1 TRUE                       969.
##  5 QRMARTSDKQQ… controllerTyp…           2     1 TRUE                      1369.
##  6 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  7 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  8 VGRCRPIINYL… controllerTyp…           2     1 TRUE                      1102.
##  9 QRLDEHCVGVG… controllerTyp…           3     1 TRUE                       713.
## 10 VDYQGKKVVII… controllerTyp…           4     1 TRUE                       870.
## # … with 2,741 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
</div>
<div id="remove-non-proteotypic-peptides" class="section level3">
<h3 class="hasAnchor">
<a href="#remove-non-proteotypic-peptides" class="anchor"></a>Remove non-proteotypic peptides</h3>
<p>The scans below are those that match different proteins. For example scan 4884 (the two first rows) matches proteins <code>XXX_ECA3406</code> and <code>ECA3415</code>. Scan 4099 (rows 6 to 8) match <code>XXX_ECA4416_1</code>, <code>XXX_ECA4416_2</code> and <code>XXX_ECA4416_3</code>.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mltm</span> <span class="op">&lt;-</span>
    <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">spectrumID</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span>nProts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mzR/man/mzR-class.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">DatabaseAccess</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">nProts</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">DatabaseAccess</span>, <span class="va">nProts</span><span class="op">)</span></code></pre></div>
<pre><code>## Adding missing grouping variables: `spectrumID`</code></pre>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mltm</span></code></pre></div>
<pre><code>## # A tibble: 85 x 3
## # Groups:   spectrumID [39]
##    spectrumID                                    DatabaseAccess nProts
##    &lt;chr&gt;                                         &lt;chr&gt;           &lt;int&gt;
##  1 controllerType=0 controllerNumber=1 scan=1073 ECA2869             2
##  2 controllerType=0 controllerNumber=1 scan=1073 ECA4278             2
##  3 controllerType=0 controllerNumber=1 scan=6578 ECA3480             2
##  4 controllerType=0 controllerNumber=1 scan=6578 ECA3481             2
##  5 controllerType=0 controllerNumber=1 scan=5617 ECA4283             2
##  6 controllerType=0 controllerNumber=1 scan=5617 ECA4292             2
##  7 controllerType=0 controllerNumber=1 scan=3926 ECA0216             2
##  8 controllerType=0 controllerNumber=1 scan=3926 ECA4035             2
##  9 controllerType=0 controllerNumber=1 scan=4784 ECA0216             2
## 10 controllerType=0 controllerNumber=1 scan=4784 ECA4035             2
## # … with 75 more rows</code></pre>
<p>We can now remove the scane with</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id_tbl</span> <span class="op">&lt;-</span>
    <span class="va">id_tbl</span> <span class="op">%&gt;%</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="op">!</span><span class="va">spectrumID</span> <span class="op">%in%</span> <span class="va">mltm</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span>
<span class="va">id_tbl</span></code></pre></div>
<pre><code>## # A tibble: 2,666 x 35
##    sequence     spectrumID     chargeState  rank passThreshold experimentalMass…
##    &lt;chr&gt;        &lt;chr&gt;                &lt;int&gt; &lt;int&gt; &lt;lgl&gt;                     &lt;dbl&gt;
##  1 RQCRTDFLNYLR controllerTyp…           3     1 TRUE                       548.
##  2 ESVALADQVTC… controllerTyp…           2     1 TRUE                      1288.
##  3 QRMARTSDKQQ… controllerTyp…           3     1 TRUE                       913.
##  4 DGGPAIYGHER… controllerTyp…           3     1 TRUE                       969.
##  5 QRMARTSDKQQ… controllerTyp…           2     1 TRUE                      1369.
##  6 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  7 CIDRARHVEVQ… controllerTyp…           3     1 TRUE                      1285.
##  8 VGRCRPIINYL… controllerTyp…           2     1 TRUE                      1102.
##  9 QRLDEHCVGVG… controllerTyp…           3     1 TRUE                       713.
## 10 VDYQGKKVVII… controllerTyp…           4     1 TRUE                       870.
## # … with 2,656 more rows, and 29 more variables: calculatedMassToCharge &lt;dbl&gt;,
## #   peptideRef &lt;chr&gt;, modNum &lt;int&gt;, isDecoy &lt;lgl&gt;, post &lt;chr&gt;, pre &lt;chr&gt;,
## #   start &lt;int&gt;, end &lt;int&gt;, DatabaseAccess &lt;chr&gt;, DBseqLength &lt;int&gt;,
## #   DatabaseSeq &lt;chr&gt;, DatabaseDescription &lt;chr&gt;, scan.number.s. &lt;dbl&gt;,
## #   acquisitionNum &lt;dbl&gt;, spectrumFile &lt;chr&gt;, idFile &lt;chr&gt;,
## #   MS.GF.RawScore &lt;dbl&gt;, MS.GF.DeNovoScore &lt;dbl&gt;, MS.GF.SpecEValue &lt;dbl&gt;,
## #   MS.GF.EValue &lt;dbl&gt;, MS.GF.QValue &lt;dbl&gt;, MS.GF.PepQValue &lt;dbl&gt;,
## #   modPeptideRef &lt;chr&gt;, modName &lt;chr&gt;, modMass &lt;dbl&gt;, modLocation &lt;int&gt;,
## #   subOriginalResidue &lt;chr&gt;, subReplacementResidue &lt;chr&gt;, subLocation &lt;int&gt;</code></pre>
<p>Which leaves us with 2666 PSMs.</p>
<p>This can also be achieved with the <code><a href="../reference/filterPSMs.html">filterPSMs()</a></code> function:</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span></code></pre></div>
<pre><code>## Starting with 5802 PSMs:</code></pre>
<pre><code>##  removed 2896 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2666 PSMs left.</code></pre>
</div>
</div>
</div>
<div id="the-mzr-and-mzid-parsers" class="section level1">
<h1 class="hasAnchor">
<a href="#the-mzr-and-mzid-parsers" class="anchor"></a>The <code>mzR</code> and <code>mzID</code> parsers</h1>
<p>The <code><a href="../reference/PSM.html">readPSMs()</a></code> function can take two different values for the <code>parser</code> parameter, namely <code>"mzR"</code> (which is also the default value) and <code>"mzID"</code>.</p>
<ul>
<li><p><strong>mzR</strong> uses the <code><a href="https://rdrr.io/pkg/mzR/man/openMSfile.html" class="external-link">openIDfile()</a></code> function from the <em><a href="https://bioconductor.org/packages/3.13/mzR" class="external-link">mzR</a></em> to parse the <code>mzId</code> file(s), and then coerces the data to a <code>data.frame</code> which is eventually returned as a <code>DataFrame</code>. The parser function uses dedicated code from the Proteowizard project (included in <code>mzR</code>) and is generally the fastest approach.</p></li>
<li><p><strong>mzID</strong> parses the <code>mzId</code> file with <code>mzID()</code> function from the <em><a href="https://bioconductor.org/packages/3.13/mzID" class="external-link">mzID</a></em> package, and the flattens the data to a <code>data.frame</code> with <code><a href="https://rdrr.io/pkg/mzID/man/flatten.html" class="external-link">mzID::flatten()</a></code> and eventuelly returns a <code>DataFrame</code>. The <code>mzID</code> package relies on the <em><a href="https://CRAN.R-project.org/package=XML" class="external-link">XML</a></em> package. Is is slower but is is more robust to variations in the <code>mzID</code> implementation, as is a useful backup when the <code>mzR</code> approach fails with errors.</p></li>
</ul>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/system.time.html" class="external-link">system.time</a></span><span class="op">(</span><span class="va">id1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/PSM.html">readPSMs</a></span><span class="op">(</span><span class="va">f</span>, parser <span class="op">=</span> <span class="st">"mzR"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##    user  system elapsed 
##   0.263   0.008   0.271</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/system.time.html" class="external-link">system.time</a></span><span class="op">(</span><span class="va">id2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/PSM.html">readPSMs</a></span><span class="op">(</span><span class="va">f</span>, parser <span class="op">=</span> <span class="st">"mzID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Loading required namespace: mzID</code></pre>
<pre><code>## reading TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid... DONE!</code></pre>
<pre><code>##    user  system elapsed 
##   6.624   0.132   6.757</code></pre>
<p>Other differences in the two parsers include the columns that are returned, way they name them, and, as will shown below the matches that are returned. Below, note for instance (and this will be important later), that there is not equivalent of <code>"modLocation"</code> in <code>id2</code>.</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "sequence"                 "spectrumID"              
##  [3] "chargeState"              "rank"                    
##  [5] "passThreshold"            "experimentalMassToCharge"
##  [7] "calculatedMassToCharge"   "peptideRef"              
##  [9] "modNum"                   "isDecoy"                 
## [11] "post"                     "pre"                     
## [13] "start"                    "end"                     
## [15] "DatabaseAccess"           "DBseqLength"             
## [17] "DatabaseSeq"              "DatabaseDescription"     
## [19] "scan.number.s."           "acquisitionNum"          
## [21] "spectrumFile"             "idFile"                  
## [23] "MS.GF.RawScore"           "MS.GF.DeNovoScore"       
## [25] "MS.GF.SpecEValue"         "MS.GF.EValue"            
## [27] "MS.GF.QValue"             "MS.GF.PepQValue"         
## [29] "modPeptideRef"            "modName"                 
## [31] "modMass"                  "modLocation"             
## [33] "subOriginalResidue"       "subReplacementResidue"   
## [35] "subLocation"</code></pre>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "spectrumid"                "scan number(s)"           
##  [3] "acquisitionnum"            "passthreshold"            
##  [5] "rank"                      "calculatedmasstocharge"   
##  [7] "experimentalmasstocharge"  "chargestate"              
##  [9] "ms-gf:denovoscore"         "ms-gf:evalue"             
## [11] "ms-gf:pepqvalue"           "ms-gf:qvalue"             
## [13] "ms-gf:rawscore"            "ms-gf:specevalue"         
## [15] "assumeddissociationmethod" "isotopeerror"             
## [17] "isdecoy"                   "post"                     
## [19] "pre"                       "end"                      
## [21] "start"                     "accession"                
## [23] "length"                    "description"              
## [25] "pepseq"                    "modified"                 
## [27] "modification"              "idFile"                   
## [29] "spectrumFile"              "databaseFile"</code></pre>
<p>We also have different number of matches in the two tables:</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 5802</code></pre>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">id2</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 5759</code></pre>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id1</span><span class="op">$</span><span class="va">isDecoy</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2906  2896</code></pre>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id2</span><span class="op">$</span><span class="va">isdecoy</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  2886  2873</code></pre>
<p>Let’s first filter the PSM tables to facilitate focus the comparison of relevant scans. Note that the default <code><a href="../reference/filterPSMs.html">filterPSMs()</a></code> arguments are set to work with the <code>mzR</code> parser.</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id1_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id1</span><span class="op">)</span></code></pre></div>
<pre><code>## Starting with 5802 PSMs:</code></pre>
<pre><code>##  removed 2896 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2666 PSMs left.</code></pre>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id2_filtered</span> <span class="op">&lt;-</span>
    <span class="fu"><a href="../reference/filterPSMs.html">filterPSMs</a></span><span class="op">(</span><span class="va">id2</span>, decoy <span class="op">=</span> <span class="st">"isdecoy"</span>,
           accession <span class="op">=</span> <span class="st">"accession"</span>,
           spectrumID <span class="op">=</span> <span class="st">"spectrumid"</span><span class="op">)</span></code></pre></div>
<pre><code>## Starting with 5759 PSMs:</code></pre>
<pre><code>##  removed 2873 decoy hits</code></pre>
<pre><code>##  removed 155 PSMs with rank &gt; 1</code></pre>
<pre><code>##  removed 85 non-proteotypic peptides</code></pre>
<pre><code>## 2646 PSMs left.</code></pre>
<p>As can be seen, we are also left with 2666 vs 2646 PSMs after filtering.</p>
<p>The difference doesn’t stem from different scans, given that the spectum identifiers are identical in both tables:</p>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/identical.html" class="external-link">identical</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html" class="external-link">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span>,
          <span class="fu"><a href="https://rdrr.io/r/base/sort.html" class="external-link">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">id2_filtered</span><span class="op">$</span><span class="va">spectrumid</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>The difference is obvious when we tally a table of spectrum ids occurences in the filtered tables. In <code>id2_filtered</code>, each scan is unique, i.e matched only once.</p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html" class="external-link">anyDuplicated</a></span><span class="op">(</span><span class="va">id2_filtered</span><span class="op">$</span><span class="va">spectrumid</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>However, for <code>id1_filtered</code>, we see that some scans are still repeat up to 4 times in the table:</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##    1    2    3    4 
## 2630   13    2    1</code></pre>
<p>The example below shows that these differences stem from the modification location (<code>"modLocation"</code>), that is not report by the <code>mzID</code> parser:</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/which.html" class="external-link">which</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html" class="external-link">table</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span><span class="op">)</span> <span class="op">==</span> <span class="fl">4</span><span class="op">)</span><span class="op">)</span>
<span class="va">id1_filtered</span><span class="op">[</span><span class="va">id1_filtered</span><span class="op">$</span><span class="va">spectrumID</span> <span class="op">==</span> <span class="va">k</span>, <span class="op">]</span></code></pre></div>
<pre><code>## PSM with 4 rows and 35 columns.
## names(35): sequence spectrumID ... subReplacementResidue subLocation</code></pre>
<p>If we remove the <code>"modLocation"</code> column, we recoved the same number of PSMs than with the <code>mzID</code> parser.</p>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">id1_filtered</span><span class="op">$</span><span class="va">modLocation</span> <span class="op">&lt;-</span> <span class="cn">NULL</span>
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">id1_filtered</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 2646</code></pre>
</div>
<div id="session-information" class="section level1">
<h1 class="hasAnchor">
<a href="#session-information" class="anchor"></a>Session information</h1>
<div class="sourceCode" id="cb83"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html" class="external-link">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## R Under development (unstable) (2021-03-18 r80099)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.2 LTS
## 
## Matrix products: default
## BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
## [1] dplyr_1.0.5         PSM_0.3.0           S4Vectors_0.29.9   
## [4] BiocGenerics_0.37.1 BiocStyle_2.19.1   
## 
## loaded via a namespace (and not attached):
##  [1] MatrixGenerics_1.3.1         Biobase_2.51.0              
##  [3] tidyr_1.1.3                  sass_0.3.1                  
##  [5] foreach_1.5.1                jsonlite_1.7.2              
##  [7] bslib_0.2.4                  assertthat_0.2.1            
##  [9] BiocManager_1.30.10          msdata_0.31.1               
## [11] GenomeInfoDbData_1.2.4       yaml_2.2.1                  
## [13] pillar_1.5.1                 lattice_0.20-41             
## [15] glue_1.4.2                   digest_0.6.27               
## [17] GenomicRanges_1.43.3         XVector_0.31.1              
## [19] plyr_1.8.6                   htmltools_0.5.1.1           
## [21] Matrix_1.3-2                 XML_3.99-0.6                
## [23] pkgconfig_2.0.3              bookdown_0.21               
## [25] zlibbioc_1.37.0              purrr_0.3.4                 
## [27] MultiAssayExperiment_1.17.18 BiocParallel_1.25.5         
## [29] tibble_3.1.0                 generics_0.1.0              
## [31] AnnotationFilter_1.15.0      IRanges_2.25.6              
## [33] ellipsis_0.3.1               cachem_1.0.4                
## [35] SummarizedExperiment_1.21.1  lazyeval_0.2.2              
## [37] cli_2.3.1                    magrittr_2.0.1              
## [39] crayon_1.4.1                 ps_1.6.0                    
## [41] memoise_2.0.0                evaluate_0.14               
## [43] fs_1.5.0                     ncdf4_1.17                  
## [45] fansi_0.4.2                  doParallel_1.0.16           
## [47] MASS_7.3-53.1                QFeatures_1.1.2             
## [49] mzR_2.25.3                   textshaping_0.3.3           
## [51] tools_4.1.0                  lifecycle_1.0.0             
## [53] matrixStats_0.58.0           stringr_1.4.0               
## [55] cluster_2.1.1                DelayedArray_0.17.9         
## [57] compiler_4.1.0               pkgdown_1.6.1.9001          
## [59] jquerylib_0.1.3              GenomeInfoDb_1.27.8         
## [61] mzID_1.29.0                  systemfonts_1.0.1           
## [63] rlang_0.4.10                 grid_4.1.0                  
## [65] RCurl_1.98-1.3               iterators_1.0.13            
## [67] rstudioapi_0.13              MsCoreUtils_1.3.3           
## [69] bitops_1.0-6                 rmarkdown_2.7               
## [71] codetools_0.2-18             DBI_1.1.1                   
## [73] R6_2.5.0                     knitr_1.31                  
## [75] fastmap_1.1.0                utf8_1.2.1                  
## [77] clue_0.3-58                  rprojroot_2.0.2             
## [79] ragg_1.1.2                   ProtGenerics_1.23.7         
## [81] desc_1.3.0                   stringi_1.5.3               
## [83] Rcpp_1.0.6                   vctrs_0.3.6                 
## [85] tidyselect_1.1.0             xfun_0.22</code></pre>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>The rownames aren’t needed here are are removed to reduce to output in the the next code chunk display parts of <code>id2</code>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p></p>
<p>Developed by Laurent Gatto, Johannes Rainer, Sebastian Gibb.</p>
</div>

<div class="pkgdown">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link external-link">pkgdown</a> 1.6.1.9001.</p>
</div>

      </footer>
</div>

  


  

  </body>
</html>
